export { default as CTable } from "./Table/ui/CTable.vue"
export { CHeader } from "./header"
export { CFooter } from "./footer"
export { CHero } from "./hero"
export { WhyChooseUs } from "./whychooseus"
export { CCallToAction } from "./calltoaction"
export { CAiAgents } from "./aiagents"
export { CAiModels } from "./aimodels"
export { CLandingIntro } from "./landingintro"
export { CBlogCards } from "./blogcards"
export { CPricingList } from "./pricing"
export { CAboutUsCards } from "./aboutuscards"
export { CAboutUsStory } from "./aboutusstory"
export { CCallToAgent } from "./call-to-agent"
